---
- name: "Load a variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: "Become section"
  block:
    - name: "Enable EPEL repository"
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: "present"
        lock_timeout: 180

    - name: "Install requirements"
      package:
        name: "{{ requirements }}"
        state: "present"
        lock_timeout: 180
  become: True
